export const EMOJI_CATEGORIES = [
  { id: "recent", name: "Quick Reactions", icon: "⚡" },
  { id: "smileys", name: "Smileys & Emotion", icon: "😀" },
  { id: "people", name: "People & Body", icon: "👋" },
  { id: "animals", name: "Animals & Nature", icon: "🐶" },
  { id: "food", name: "Food & Drink", icon: "🍔" },
  { id: "activities", name: "Activities", icon: "⚽" },
  { id: "travel", name: "Travel & Places", icon: "✈️" },
  { id: "objects", name: "Objects & Tech", icon: "💡" },
  { id: "symbols", name: "Symbols & Hearts", icon: "❤️" },
  { id: "flags", name: "Flags", icon: "🚩" },
];

export const QUICK_REACTIONS = ["❤️", "👍", "😂", "😮", "😢", "🙏", "🔥", "🎉", "👏", "😍", "🥳", "✨"];

export const EMOJIS = [
  // Smileys & Emotion
  { char: "😀", name: "grinning face", category: "smileys", keywords: ["smile", "happy", "grin"] },
  { char: "😃", name: "grinning face with big eyes", category: "smileys", keywords: ["smile", "happy", "joy"] },
  { char: "😄", name: "grinning face with smiling eyes", category: "smileys", keywords: ["smile", "happy", "laugh"] },
  { char: "😁", name: "beaming face with smiling eyes", category: "smileys", keywords: ["grin", "smile", "teeth"] },
  { char: "😆", name: "grinning squinting face", category: "smileys", keywords: ["laugh", "xd", "happy"] },
  { char: "😅", name: "grinning face with sweat", category: "smileys", keywords: ["sweat", "relief", "nervous"] },
  { char: "🤣", name: "rolling on the floor laughing", category: "smileys", keywords: ["rofl", "lol", "laugh", "funny"] },
  { char: "😂", name: "face with tears of joy", category: "smileys", keywords: ["cry", "laugh", "tears", "lol", "funny"] },
  { char: "🙂", name: "slightly smiling face", category: "smileys", keywords: ["smile", "happy", "kind"] },
  { char: "🙃", name: "upside down face", category: "smileys", keywords: ["silly", "sarcasm", "irony"] },
  { char: "😉", name: "winking face", category: "smileys", keywords: ["wink", "flirt", "joke"] },
  { char: "😊", name: "smiling face with smiling eyes", category: "smileys", keywords: ["blush", "smile", "happy", "warm"] },
  { char: "😇", name: "smiling face with halo", category: "smileys", keywords: ["angel", "innocent", "halo"] },
  { char: "🥰", name: "smiling face with hearts", category: "smileys", keywords: ["love", "crush", "adore", "hearts"] },
  { char: "😍", name: "smiling face with heart-eyes", category: "smileys", keywords: ["love", "heart", "crush", "in love"] },
  { char: "🤩", name: "star-struck", category: "smileys", keywords: ["stars", "excited", "wow", "amazing"] },
  { char: "😘", name: "face blowing a kiss", category: "smileys", keywords: ["kiss", "love", "flirt"] },
  { char: "😗", name: "kissing face", category: "smileys", keywords: ["kiss", "whistle"] },
  { char: "😚", name: "kissing face with closed eyes", category: "smileys", keywords: ["kiss", "love", "affection"] },
  { char: "😙", name: "kissing face with smiling eyes", category: "smileys", keywords: ["kiss", "smile"] },
  { char: "😋", name: "face savoring food", category: "smileys", keywords: ["yum", "delicious", "tasty", "tongue"] },
  { char: "😛", name: "face with tongue", category: "smileys", keywords: ["tongue", "playful", "silly"] },
  { char: "😜", name: "winking face with tongue", category: "smileys", keywords: ["wink", "tongue", "crazy", "joke"] },
  { char: "🤪", name: "zany face", category: "smileys", keywords: ["goofy", "crazy", "wild"] },
  { char: "😝", name: "squinting face with tongue", category: "smileys", keywords: ["tongue", "playful", "lol"] },
  { char: "🤑", name: "money-mouth face", category: "smileys", keywords: ["money", "rich", "dollar"] },
  { char: "🤗", name: "smiling face with open hands", category: "smileys", keywords: ["hug", "embrace", "welcome"] },
  { char: "🤭", name: "face with hand over mouth", category: "smileys", keywords: ["oops", "giggle", "secret"] },
  { char: "🤫", name: "shushing face", category: "smileys", keywords: ["shh", "quiet", "secret", "silence"] },
  { char: "🤔", name: "thinking face", category: "smileys", keywords: ["think", "hmm", "ponder", "wonder"] },
  { char: "🤐", name: "zipper-mouth face", category: "smileys", keywords: ["zip", "quiet", "secret", "mute"] },
  { char: "🤨", name: "face with raised eyebrow", category: "smileys", keywords: ["skeptical", "suspicious", "doubt"] },
  { char: "😐", name: "neutral face", category: "smileys", keywords: ["neutral", "meh", "expressionless"] },
  { char: "😑", name: "expressionless face", category: "smileys", keywords: ["blank", "done", "serious"] },
  { char: "😶", name: "face without mouth", category: "smileys", keywords: ["speechless", "silent"] },
  { char: "😏", name: "smirking face", category: "smileys", keywords: ["smirk", "flirt", "sly"] },
  { char: "😒", name: "unamused face", category: "smileys", keywords: ["bored", "annoyed", "unimpressed"] },
  { char: "🙄", name: "face with rolling eyes", category: "smileys", keywords: ["eye roll", "whatever", "sarcastic"] },
  { char: "😬", name: "grimacing face", category: "smileys", keywords: ["grimace", "awkward", "nervous"] },
  { char: "🤥", name: "lying face", category: "smileys", keywords: ["liar", "pinocchio", "fake"] },
  { char: "😌", name: "relieved face", category: "smileys", keywords: ["relieved", "calm", "peaceful"] },
  { char: "😔", name: "pensive face", category: "smileys", keywords: ["sad", "depressed", "sorry"] },
  { char: "😪", name: "sleepy face", category: "smileys", keywords: ["sleepy", "tired", "rest"] },
  { char: "🤤", name: "drooling face", category: "smileys", keywords: ["drool", "craving", "sleep"] },
  { char: "😴", name: "sleeping face", category: "smileys", keywords: ["sleep", "zzz", "night"] },
  { char: "😷", name: "face with medical mask", category: "smileys", keywords: ["mask", "sick", "covid"] },
  { char: "🤒", name: "face with thermometer", category: "smileys", keywords: ["sick", "fever", "ill"] },
  { char: "🤕", name: "face with head-bandage", category: "smileys", keywords: ["hurt", "injured", "pain"] },
  { char: "🤢", name: "nauseated face", category: "smileys", keywords: ["sick", "gross", "disgust"] },
  { char: "🤮", name: "face vomiting", category: "smileys", keywords: ["puke", "vomit", "disgusted"] },
  { char: "🤧", name: "sneezing face", category: "smileys", keywords: ["sneeze", "cold", "flu"] },
  { char: "🥵", name: "hot face", category: "smileys", keywords: ["hot", "sweat", "summer"] },
  { char: "🥶", name: "cold face", category: "smileys", keywords: ["cold", "freeze", "winter"] },
  { char: "🥴", name: "woozy face", category: "smileys", keywords: ["drunk", "dizzy", "tipsy"] },
  { char: "😵", name: "face with crossed-out eyes", category: "smileys", keywords: ["dizzy", "dead", "ko"] },
  { char: "🤯", name: "exploding head", category: "smileys", keywords: ["mind blown", "shock", "boom"] },
  { char: "🤠", name: "cowboy hat face", category: "smileys", keywords: ["cowboy", "yeehaw", "western"] },
  { char: "🥳", name: "partying face", category: "smileys", keywords: ["party", "celebrate", "birthday", "cheers"] },
  { char: "😎", name: "smiling face with sunglasses", category: "smileys", keywords: ["cool", "shades", "awesome"] },
  { char: "🤓", name: "nerd face", category: "smileys", keywords: ["nerd", "geek", "glasses", "smart"] },
  { char: "🧐", name: "face with monocle", category: "smileys", keywords: ["classy", "inspect", "curious"] },
  { char: "😕", name: "confused face", category: "smileys", keywords: ["confused", "lost", "what"] },
  { char: "😟", name: "worried face", category: "smileys", keywords: ["worried", "nervous", "scared"] },
  { char: "🙁", name: "slightly frowning face", category: "smileys", keywords: ["sad", "frown", "unhappy"] },
  { char: "😮", name: "face with open mouth", category: "smileys", keywords: ["wow", "surprised", "omg"] },
  { char: "😯", name: "hushed face", category: "smileys", keywords: ["stunned", "quiet", "surprise"] },
  { char: "😲", name: "astonished face", category: "smileys", keywords: ["shocked", "amazed", "wow"] },
  { char: "😳", name: "flushed face", category: "smileys", keywords: ["blush", "embarrassed", "shy", "shocked"] },
  { char: "🥺", name: "pleading face", category: "smileys", keywords: ["puppy eyes", "please", "begging", "cute"] },
  { char: "😦", name: "frowning face with open mouth", category: "smileys", keywords: ["scared", "shocked"] },
  { char: "😧", name: "anguished face", category: "smileys", keywords: ["anguish", "pain", "sad"] },
  { char: "😨", name: "fearful face", category: "smileys", keywords: ["fear", "scared", "afraid"] },
  { char: "😰", name: "anxious face with sweat", category: "smileys", keywords: ["nervous", "anxious", "scared"] },
  { char: "😥", name: "sad but relieved face", category: "smileys", keywords: ["phew", "sweat", "relieved"] },
  { char: "😢", name: "crying face", category: "smileys", keywords: ["cry", "tear", "sad", "unhappy"] },
  { char: "😭", name: "loudly crying face", category: "smileys", keywords: ["sob", "bawl", "cry", "sad", "tears"] },
  { char: "😱", name: "face screaming in fear", category: "smileys", keywords: ["scream", "scared", "horror", "shock"] },
  { char: "😖", name: "confounded face", category: "smileys", keywords: ["frustrated", "struggle", "upset"] },
  { char: "😣", name: "persevering face", category: "smileys", keywords: ["struggle", "endure", "tired"] },
  { char: "😞", name: "disappointed face", category: "smileys", keywords: ["disappointed", "sad", "depressed"] },
  { char: "😓", name: "downcast face with sweat", category: "smileys", keywords: ["sweat", "stressed", "tired"] },
  { char: "😩", name: "weary face", category: "smileys", keywords: ["weary", "tired", "done", "whine"] },
  { char: "😫", name: "tired face", category: "smileys", keywords: ["exhausted", "tired", "sleepy"] },
  { char: "🥱", name: "yawning face", category: "smileys", keywords: ["yawn", "bored", "sleepy"] },
  { char: "😤", name: "face with steam from nose", category: "smileys", keywords: ["angry", "triumph", "proud", "frustrated"] },
  { char: "😡", name: "enraged face", category: "smileys", keywords: ["rage", "angry", "mad", "red"] },
  { char: "😠", name: "angry face", category: "smileys", keywords: ["mad", "grumpy", "annoyed"] },
  { char: "🤬", name: "face with symbols on mouth", category: "smileys", keywords: ["curse", "swear", "furious", "angry"] },
  { char: "😈", name: "smiling face with horns", category: "smileys", keywords: ["devil", "evil", "naughty"] },
  { char: "👿", name: "angry face with horns", category: "smileys", keywords: ["devil", "demon", "mad"] },
  { char: "💀", name: "skull", category: "smileys", keywords: ["dead", "skeleton", "death", "lol"] },
  { char: "☠️", name: "skull and crossbones", category: "smileys", keywords: ["danger", "pirate", "poison"] },
  { char: "💩", name: "pile of poo", category: "smileys", keywords: ["poop", "crap", "funny"] },
  { char: "🤡", name: "clown face", category: "smileys", keywords: ["clown", "circus", "fool", "joke"] },
  { char: "👻", name: "ghost", category: "smileys", keywords: ["spooky", "halloween", "spirit"] },
  { char: "👽", name: "alien", category: "smileys", keywords: ["ufo", "extraterrestrial", "space"] },
  { char: "👾", name: "alien monster", category: "smileys", keywords: ["retro", "game", "pixel", "arcade"] },
  { char: "🤖", name: "robot", category: "smileys", keywords: ["bot", "ai", "tech", "machine"] },

  // People & Body
  { char: "👋", name: "waving hand", category: "people", keywords: ["wave", "hello", "hi", "bye", "goodbye"] },
  { char: "🤚", name: "raised back of hand", category: "people", keywords: ["hand", "backhand", "stop"] },
  { char: "✋", name: "raised hand", category: "people", keywords: ["high five", "stop", "hand"] },
  { char: "🖖", name: "vulcan salute", category: "people", keywords: ["spock", "star trek", "peace"] },
  { char: "👌", name: "ok hand", category: "people", keywords: ["ok", "perfect", "good", "nice"] },
  { char: "🤌", name: "pinched fingers", category: "people", keywords: ["italian", "chef kiss", "what do you want"] },
  { char: "🤏", name: "pinching hand", category: "people", keywords: ["tiny", "little", "small"] },
  { char: "✌️", name: "victory hand", category: "people", keywords: ["peace", "v", "two", "victory"] },
  { char: "🤞", name: "crossed fingers", category: "people", keywords: ["luck", "hope", "wish"] },
  { char: "🤟", name: "love-you gesture", category: "people", keywords: ["ily", "love", "rock"] },
  { char: "🤘", name: "sign of the horns", category: "people", keywords: ["rock", "metal", "cool"] },
  { char: "🤙", name: "call me hand", category: "people", keywords: ["call", "shaka", "hang loose"] },
  { char: "👈", name: "backhand index pointing left", category: "people", keywords: ["left", "point"] },
  { char: "👉", name: "backhand index pointing right", category: "people", keywords: ["right", "point"] },
  { char: "👆", name: "backhand index pointing up", category: "people", keywords: ["up", "this"] },
  { char: "🖕", name: "middle finger", category: "people", keywords: ["rude", "finger"] },
  { char: "👇", name: "backhand index pointing down", category: "people", keywords: ["down", "point"] },
  { char: "☝️", name: "index pointing up", category: "people", keywords: ["one", "first", "up"] },
  { char: "👍", name: "thumbs up", category: "people", keywords: ["like", "yes", "approve", "good", "agree"] },
  { char: "👎", name: "thumbs down", category: "people", keywords: ["dislike", "no", "bad", "disapprove"] },
  { char: "✊", name: "raised fist", category: "people", keywords: ["power", "fist", "solidarity"] },
  { char: "👊", name: "oncoming fist", category: "people", keywords: ["punch", "brofist", "bump"] },
  { char: "🤛", name: "left-facing fist", category: "people", keywords: ["fist bump", "left"] },
  { char: "🤜", name: "right-facing fist", category: "people", keywords: ["fist bump", "right"] },
  { char: "👏", name: "clapping hands", category: "people", keywords: ["clap", "applause", "bravo", "congrats"] },
  { char: "🙌", name: "raising hands", category: "people", keywords: ["celebrate", "praise", "hooray", "cheer"] },
  { char: "👐", name: "open hands", category: "people", keywords: ["open", "hug", "jazz hands"] },
  { char: "🤲", name: "palms up together", category: "people", keywords: ["pray", "dua", "offer"] },
  { char: "🤝", name: "handshake", category: "people", keywords: ["deal", "agree", "partner", "shake"] },
  { char: "🙏", name: "folded hands", category: "people", keywords: ["pray", "please", "thanks", "namaste", "hope"] },
  { char: "✍️", name: "writing hand", category: "people", keywords: ["write", "note", "letter"] },
  { char: "💅", name: "nail polish", category: "people", keywords: ["slay", "beauty", "sassy"] },
  { char: "🤳", name: "selfie", category: "people", keywords: ["photo", "camera", "phone"] },
  { char: "💪", name: "flexed biceps", category: "people", keywords: ["strong", "muscle", "workout", "power", "flex"] },
  { char: "👀", name: "eyes", category: "people", keywords: ["look", "see", "watching", "shifty"] },
  { char: "👁️", name: "eye", category: "people", keywords: ["vision", "look", "see"] },
  { char: "👅", name: "tongue", category: "people", keywords: ["lick", "taste", "playful"] },
  { char: "👄", name: "mouth", category: "people", keywords: ["lips", "kiss", "talk"] },
  { char: "💋", name: "kiss mark", category: "people", keywords: ["kiss", "lipstick", "love"] },
  { char: "👶", name: "baby", category: "people", keywords: ["infant", "child", "cute"] },
  { char: "👧", name: "girl", category: "people", keywords: ["female", "woman", "child"] },
  { char: "👦", name: "boy", category: "people", keywords: ["male", "man", "kid"] },
  { char: "👩", name: "woman", category: "people", keywords: ["female", "lady"] },
  { char: "👨", name: "man", category: "people", keywords: ["male", "guy"] },
  { char: "🧑‍💻", name: "technologist", category: "people", keywords: ["coder", "developer", "programmer", "hacker"] },
  { char: "💃", name: "woman dancing", category: "people", keywords: ["dance", "party", "fun"] },
  { char: "🕺", name: "man dancing", category: "people", keywords: ["disco", "dance", "party"] },

  // Animals & Nature
  { char: "🐶", name: "dog face", category: "animals", keywords: ["dog", "puppy", "pet"] },
  { char: "🐱", name: "cat face", category: "animals", keywords: ["cat", "kitten", "meow"] },
  { char: "🐭", name: "mouse face", category: "animals", keywords: ["mouse", "rat"] },
  { char: "🐹", name: "hamster", category: "animals", keywords: ["hamster", "cute", "pet"] },
  { char: "🐰", name: "rabbit face", category: "animals", keywords: ["bunny", "rabbit", "easter"] },
  { char: "🦊", name: "fox", category: "animals", keywords: ["fox", "clever"] },
  { char: "🐻", name: "bear", category: "animals", keywords: ["bear", "teddy"] },
  { char: "🐼", name: "panda", category: "animals", keywords: ["panda", "cute", "bamboo"] },
  { char: "🐨", name: "koala", category: "animals", keywords: ["koala", "australia"] },
  { char: "🐯", name: "tiger face", category: "animals", keywords: ["tiger", "cat", "wild"] },
  { char: "🦁", name: "lion", category: "animals", keywords: ["lion", "king", "roar"] },
  { char: "🐮", name: "cow face", category: "animals", keywords: ["cow", "moo", "milk"] },
  { char: "🐷", name: "pig face", category: "animals", keywords: ["pig", "oink"] },
  { char: "🐸", name: "frog", category: "animals", keywords: ["frog", "toad", "croak"] },
  { char: "🐵", name: "monkey face", category: "animals", keywords: ["monkey", "ape"] },
  { char: "🙈", name: "see-no-evil monkey", category: "animals", keywords: ["shy", "hide", "oops"] },
  { char: "🙉", name: "hear-no-evil monkey", category: "animals", keywords: ["loud", "cant hear"] },
  { char: "🙊", name: "speak-no-evil monkey", category: "animals", keywords: ["quiet", "secret", "shh"] },
  { char: "🐔", name: "chicken", category: "animals", keywords: ["chicken", "hen", "bird"] },
  { char: "🐧", name: "penguin", category: "animals", keywords: ["penguin", "ice", "bird"] },
  { char: "🐦", name: "bird", category: "animals", keywords: ["bird", "tweet"] },
  { char: "🦆", name: "duck", category: "animals", keywords: ["duck", "quack"] },
  { char: "🦅", name: "eagle", category: "animals", keywords: ["eagle", "bird", "fly"] },
  { char: "🦉", name: "owl", category: "animals", keywords: ["owl", "night", "wise"] },
  { char: "🦄", name: "unicorn", category: "animals", keywords: ["magic", "fantasy", "rainbow"] },
  { char: "🐝", name: "honeybee", category: "animals", keywords: ["bee", "honey", "buzz"] },
  { char: "🦋", name: "butterfly", category: "animals", keywords: ["butterfly", "pretty", "wings"] },
  { char: "🐢", name: "turtle", category: "animals", keywords: ["turtle", "slow", "shell"] },
  { char: "🐍", name: "snake", category: "animals", keywords: ["snake", "reptile"] },
  { char: "🐬", name: "dolphin", category: "animals", keywords: ["dolphin", "ocean", "swim"] },
  { char: "🐳", name: "spouting whale", category: "animals", keywords: ["whale", "ocean", "water"] },
  { char: "🦈", name: "shark", category: "animals", keywords: ["shark", "ocean", "danger"] },
  { char: "🌸", name: "cherry blossom", category: "animals", keywords: ["flower", "pink", "spring"] },
  { char: "🌹", name: "rose", category: "animals", keywords: ["rose", "flower", "red", "love"] },
  { char: "🌻", name: "sunflower", category: "animals", keywords: ["sunflower", "summer", "yellow"] },
  { char: "🌲", name: "evergreen tree", category: "animals", keywords: ["tree", "nature", "forest"] },
  { char: "🌴", name: "palm tree", category: "animals", keywords: ["palm", "beach", "tropical", "vacation"] },
  { char: "🍀", name: "four leaf clover", category: "animals", keywords: ["clover", "lucky", "luck"] },

  // Food & Drink
  { char: "🍎", name: "red apple", category: "food", keywords: ["apple", "fruit", "red"] },
  { char: "🍌", name: "banana", category: "food", keywords: ["banana", "fruit", "yellow"] },
  { char: "🍉", name: "watermelon", category: "food", keywords: ["watermelon", "melon", "fruit"] },
  { char: "🍇", name: "grapes", category: "food", keywords: ["grapes", "fruit", "wine"] },
  { char: "🍓", name: "strawberry", category: "food", keywords: ["strawberry", "berry", "fruit"] },
  { char: "🥭", name: "mango", category: "food", keywords: ["mango", "fruit", "tropical"] },
  { char: "🍍", name: "pineapple", category: "food", keywords: ["pineapple", "fruit"] },
  { char: "🥑", name: "avocado", category: "food", keywords: ["avocado", "guacamole"] },
  { char: "🍔", name: "hamburger", category: "food", keywords: ["burger", "fast food", "beef"] },
  { char: "🍟", name: "french fries", category: "food", keywords: ["fries", "chips", "fast food"] },
  { char: "🍕", name: "pizza", category: "food", keywords: ["pizza", "cheese", "slice", "italian"] },
  { char: "🌭", name: "hot dog", category: "food", keywords: ["hotdog", "sausage", "fast food"] },
  { char: "🥪", name: "sandwich", category: "food", keywords: ["sandwich", "lunch", "bread"] },
  { char: "🌮", name: "taco", category: "food", keywords: ["taco", "mexican", "food"] },
  { char: "🌯", name: "burrito", category: "food", keywords: ["burrito", "wrap", "mexican"] },
  { char: "🍜", name: "steaming bowl", category: "food", keywords: ["ramen", "noodles", "soup"] },
  { char: "🍝", name: "spaghetti", category: "food", keywords: ["pasta", "italian", "noodles"] },
  { char: "🍣", name: "sushi", category: "food", keywords: ["sushi", "japanese", "fish"] },
  { char: "🍦", name: "soft ice cream", category: "food", keywords: ["ice cream", "dessert", "sweet"] },
  { char: "🍩", name: "doughnut", category: "food", keywords: ["donut", "sweet", "dessert"] },
  { char: "🍪", name: "cookie", category: "food", keywords: ["cookie", "biscuit", "chocolate"] },
  { char: "🎂", name: "birthday cake", category: "food", keywords: ["cake", "birthday", "party"] },
  { char: "🍫", name: "chocolate bar", category: "food", keywords: ["chocolate", "candy", "sweet"] },
  { char: "🍿", name: "popcorn", category: "food", keywords: ["popcorn", "movie", "snack"] },
  { char: "☕", name: "hot beverage", category: "food", keywords: ["coffee", "tea", "cafe"] },
  { char: "🧋", name: "bubble tea", category: "food", keywords: ["boba", "tea", "drink"] },
  { char: "🥤", name: "cup with straw", category: "food", keywords: ["soda", "juice", "drink"] },
  { char: "🍺", name: "beer mug", category: "food", keywords: ["beer", "alcohol", "cheers"] },
  { char: "🍻", name: "clinking beer mugs", category: "food", keywords: ["cheers", "beers", "party"] },
  { char: "🍷", name: "wine glass", category: "food", keywords: ["wine", "alcohol", "drink"] },

  // Activities & Sports
  { char: "⚽", name: "soccer ball", category: "activities", keywords: ["football", "soccer", "ball"] },
  { char: "🏀", name: "basketball", category: "activities", keywords: ["basketball", "nba", "ball"] },
  { char: "🏈", name: "american football", category: "activities", keywords: ["nfl", "football", "superbowl"] },
  { char: "⚾", name: "baseball", category: "activities", keywords: ["baseball", "mlb", "ball"] },
  { char: "🎾", name: "tennis", category: "activities", keywords: ["tennis", "racket", "ball"] },
  { char: "🏐", name: "volleyball", category: "activities", keywords: ["volleyball", "beach"] },
  { char: "🏏", name: "cricket game", category: "activities", keywords: ["cricket", "bat", "ipl"] },
  { char: "🏓", name: "ping pong", category: "activities", keywords: ["table tennis", "paddle"] },
  { char: "🏸", name: "badminton", category: "activities", keywords: ["badminton", "shuttlecock"] },
  { char: "🥊", name: "boxing glove", category: "activities", keywords: ["boxing", "fight", "punch"] },
  { char: "🎮", name: "video game", category: "activities", keywords: ["game", "gaming", "controller", "playstation", "xbox"] },
  { char: "🎯", name: "bullseye", category: "activities", keywords: ["target", "darts", "hit", "goal"] },
  { char: "🎲", name: "game die", category: "activities", keywords: ["dice", "game", "luck"] },
  { char: "🏆", name: "trophy", category: "activities", keywords: ["winner", "champion", "first", "gold"] },
  { char: "🥇", name: "1st place medal", category: "activities", keywords: ["gold", "medal", "first"] },
  { char: "🎨", name: "artist palette", category: "activities", keywords: ["art", "paint", "draw"] },
  { char: "🎬", name: "clapper board", category: "activities", keywords: ["movie", "cinema", "film"] },
  { char: "🎤", name: "microphone", category: "activities", keywords: ["sing", "karaoke", "music", "mic"] },
  { char: "🎧", name: "headphone", category: "activities", keywords: ["music", "listen", "audio"] },
  { char: "🎸", name: "guitar", category: "activities", keywords: ["guitar", "rock", "music"] },

  // Travel & Places
  { char: "🚗", name: "automobile", category: "travel", keywords: ["car", "drive", "vehicle"] },
  { char: "🚕", name: "taxi", category: "travel", keywords: ["cab", "taxi", "uber"] },
  { char: "🚌", name: "bus", category: "travel", keywords: ["bus", "transport"] },
  { char: "🏎️", name: "racing car", category: "travel", keywords: ["f1", "race", "speed"] },
  { char: "🚓", name: "police car", category: "travel", keywords: ["police", "cop", "emergency"] },
  { char: "🚑", name: "ambulance", category: "travel", keywords: ["ambulance", "hospital", "emergency"] },
  { char: "🚒", name: "fire engine", category: "travel", keywords: ["fire", "truck", "emergency"] },
  { char: "🚲", name: "bicycle", category: "travel", keywords: ["bike", "cycling", "ride"] },
  { char: "🛵", name: "motor scooter", category: "travel", keywords: ["scooter", "vespa"] },
  { char: "🏍️", name: "motorcycle", category: "travel", keywords: ["bike", "motorcycle", "moto"] },
  { char: "✈️", name: "airplane", category: "travel", keywords: ["flight", "plane", "travel", "fly", "trip"] },
  { char: "🚀", name: "rocket", category: "travel", keywords: ["rocket", "space", "launch", "fast", "moon"] },
  { char: "🛸", name: "flying saucer", category: "travel", keywords: ["ufo", "alien", "space"] },
  { char: "⛵", name: "sailboat", category: "travel", keywords: ["boat", "sea", "sailing"] },
  { char: "🚢", name: "ship", category: "travel", keywords: ["cruise", "ship", "boat"] },
  { char: "🏖️", name: "beach with umbrella", category: "travel", keywords: ["beach", "holiday", "vacation", "sea"] },
  { char: "🏝️", name: "desert island", category: "travel", keywords: ["island", "tropical", "vacation"] },
  { char: "🏕️", name: "camping", category: "travel", keywords: ["camp", "tent", "outdoors"] },
  { char: "🏙️", name: "cityscape", category: "travel", keywords: ["city", "buildings", "skyline"] },
  { char: "🏰", name: "castle", category: "travel", keywords: ["castle", "fairytale", "palace"] },

  // Objects & Tech
  { char: "📱", name: "mobile phone", category: "objects", keywords: ["iphone", "phone", "cell", "screen"] },
  { char: "💻", name: "laptop", category: "objects", keywords: ["computer", "pc", "macbook", "work"] },
  { char: "🖥️", name: "desktop computer", category: "objects", keywords: ["computer", "screen", "monitor"] },
  { char: "📷", name: "camera", category: "objects", keywords: ["photo", "picture", "shoot"] },
  { char: "📸", name: "camera with flash", category: "objects", keywords: ["photo", "flash", "selfie"] },
  { char: "📹", name: "video camera", category: "objects", keywords: ["video", "record", "movie"] },
  { char: "📺", name: "television", category: "objects", keywords: ["tv", "screen", "show"] },
  { char: "⏰", name: "alarm clock", category: "objects", keywords: ["alarm", "clock", "time", "wake"] },
  { char: "💡", name: "light bulb", category: "objects", keywords: ["idea", "light", "bright", "smart"] },
  { char: "🔦", name: "flashlight", category: "objects", keywords: ["light", "torch"] },
  { char: "💸", name: "money with wings", category: "objects", keywords: ["cash", "money", "spent", "rich"] },
  { char: "💵", name: "dollar banknote", category: "objects", keywords: ["dollar", "cash", "money"] },
  { char: "💳", name: "credit card", category: "objects", keywords: ["card", "payment", "buy"] },
  { char: "💎", name: "gem stone", category: "objects", keywords: ["diamond", "gem", "luxury", "rich"] },
  { char: "🎁", name: "wrapped gift", category: "objects", keywords: ["present", "gift", "birthday", "box"] },
  { char: "📦", name: "package", category: "objects", keywords: ["box", "delivery", "shipping", "parcel"] },
  { char: "🔒", name: "locked", category: "objects", keywords: ["lock", "security", "private", "secure"] },
  { char: "🔓", name: "unlocked", category: "objects", keywords: ["unlock", "open"] },
  { char: "🔑", name: "key", category: "objects", keywords: ["key", "password", "access"] },
  { char: "🔨", name: "hammer", category: "objects", keywords: ["tool", "build", "fix"] },
  { char: "💣", name: "bomb", category: "objects", keywords: ["explosion", "boom", "blast"] },
  { char: "💊", name: "pill", category: "objects", keywords: ["medicine", "drug", "sick"] },

  // Symbols & Hearts
  { char: "❤️", name: "red heart", category: "symbols", keywords: ["love", "heart", "like", "red"] },
  { char: "🧡", name: "orange heart", category: "symbols", keywords: ["love", "orange", "warm"] },
  { char: "💛", name: "yellow heart", category: "symbols", keywords: ["love", "friendship", "yellow"] },
  { char: "💚", name: "green heart", category: "symbols", keywords: ["love", "green", "nature"] },
  { char: "💙", name: "blue heart", category: "symbols", keywords: ["love", "blue", "trust"] },
  { char: "💜", name: "purple heart", category: "symbols", keywords: ["love", "purple", "bts"] },
  { char: "🖤", name: "black heart", category: "symbols", keywords: ["love", "black", "dark"] },
  { char: "🤍", name: "white heart", category: "symbols", keywords: ["love", "white", "pure"] },
  { char: "🤎", name: "brown heart", category: "symbols", keywords: ["love", "brown"] },
  { char: "💔", name: "broken heart", category: "symbols", keywords: ["heartbreak", "sad", "breakup"] },
  { char: "❣️", name: "heart exclamation", category: "symbols", keywords: ["love", "exclamation", "heart"] },
  { char: "💕", name: "two hearts", category: "symbols", keywords: ["love", "pink", "hearts"] },
  { char: "💞", name: "revolving hearts", category: "symbols", keywords: ["love", "hearts", "revolving"] },
  { char: "💓", name: "beating heart", category: "symbols", keywords: ["pulse", "heartbeat", "love"] },
  { char: "💗", name: "growing heart", category: "symbols", keywords: ["love", "excited", "growing"] },
  { char: "💖", name: "sparkling heart", category: "symbols", keywords: ["sparkle", "love", "shine", "pink"] },
  { char: "💘", name: "heart with arrow", category: "symbols", keywords: ["cupid", "love", "arrow"] },
  { char: "💝", name: "heart with ribbon", category: "symbols", keywords: ["gift", "love", "valentine"] },
  { char: "💯", name: "hundred points", category: "symbols", keywords: ["100", "score", "perfect", "keep it real"] },
  { char: "🔥", name: "fire", category: "symbols", keywords: ["flame", "lit", "hot", "fire", "cool"] },
  { char: "✨", name: "sparkles", category: "symbols", keywords: ["shine", "stars", "sparkle", "magic", "clean"] },
  { char: "🌟", name: "glowing star", category: "symbols", keywords: ["star", "glow", "gold"] },
  { char: "⭐", name: "star", category: "symbols", keywords: ["star", "gold", "favorite"] },
  { char: "💥", name: "collision", category: "symbols", keywords: ["boom", "crash", "explode"] },
  { char: "🎉", name: "party popper", category: "symbols", keywords: ["celebrate", "party", "congrats", "tada"] },
  { char: "🎊", name: "confetti ball", category: "symbols", keywords: ["celebrate", "party", "confetti"] },
  { char: "⚡", name: "high voltage", category: "symbols", keywords: ["lightning", "thunder", "power", "fast", "bolt"] },
  { char: "☀️", name: "sun", category: "symbols", keywords: ["sunny", "sun", "warm", "day"] },
  { char: "🌙", name: "crescent moon", category: "symbols", keywords: ["moon", "night", "dark"] },
  { char: "✔️", name: "check mark", category: "symbols", keywords: ["done", "tick", "yes", "correct"] },
  { char: "❌", name: "cross mark", category: "symbols", keywords: ["no", "wrong", "cancel", "x"] },

  // Flags
  { char: "🇮🇳", name: "flag India", category: "flags", keywords: ["india", "flag", "indian", "tiranga", "bharat"] },
  { char: "🇺🇸", name: "flag United States", category: "flags", keywords: ["usa", "america", "flag", "us"] },
  { char: "🇬🇧", name: "flag United Kingdom", category: "flags", keywords: ["uk", "britain", "england", "flag"] },
  { char: "🇨🇦", name: "flag Canada", category: "flags", keywords: ["canada", "flag"] },
  { char: "🇦🇺", name: "flag Australia", category: "flags", keywords: ["australia", "flag"] },
  { char: "🇩🇪", name: "flag Germany", category: "flags", keywords: ["germany", "flag"] },
  { char: "🇫🇷", name: "flag France", category: "flags", keywords: ["france", "french", "flag"] },
  { char: "🇯🇵", name: "flag Japan", category: "flags", keywords: ["japan", "japanese", "flag"] },
  { char: "🇧🇷", name: "flag Brazil", category: "flags", keywords: ["brazil", "flag"] },
  { char: "🚩", name: "triangular flag", category: "flags", keywords: ["red flag", "flag", "point"] },
  { char: "🏁", name: "chequered flag", category: "flags", keywords: ["race", "finish", "winner"] },
];
